export class User{ // userId generated by `_id` by mongoDb
    constructor(admin, corpo, trendy, normal, userName, cash, picture, bio, following, interests, password){
        this.admin = admin;
        this.corpo = corpo;
        this.trendy = trendy;
        this.normal = normal;
        this.userName = userName;
        this.cash = cash;
        this.picture = picture;
        this.bio = bio;
        this.following = following;
        this.likes = 0;
        this.interests = interests;
        this.password = hash(password);
    }
    updateWith(otherUser) {
        Object.assign(this, otherUser);
    }
    hash(text) {
        const hash = crypto.createHash('sha256');
        hash.update(text);
        return hash.digest('hex');
    }
}